### ISSUE TITLE
Not working on Internet Explorer?

### ISSUE THREAD

**Issue by marcoherbst** [evercam/wicklowcam#9]

**Comment by asimism** [comment]
This is due to meta tag <meta content='IE=EmulateIE7' http-equiv='X-UA-Compatible' />
We should remove this tag to fix the issue. Actually this tag was forcing the browser to go in IE7 compatibility mode instead of rendering in the default IE mode (version installed).

**Comment by marcoherbst** [comment]
Sounds good. Tks. M

**Comment by marcoherbst** [comment]
Fixed by @asimism in https://github.com/evercam/wicklowcam/pull/14
